apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c44s1jfbu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c44s1jfbu-python 
  name: c44s1jfbu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c44s1jfbu-python 
